# This is a Docker Compose configuration
# intended for development purposes

version: '3'

volumes:
  db: {}

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookstack-test
      MYSQL_USER: bookstack-test
      MYSQL_PASSWORD: bookstack-test
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - ${DEV_PORT}:80
    volumes:
      - ./:/app
    entrypoint: /app/docker/dev/entrypoint.app.sh
  node:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: /app/docker/dev/entrypoint.node.sh
